scarlet/blend.py, scarlet/transformations.py
Transformation matrices get on-the-fly cache to reduce construction cost.
As a side consequence, `Blend` needs a new keyword `source_sizes` to know which sizes are allowed according to a predefined list.
To work best, `Source` initialization needs to respect the same size options, which needs to get fixed when #28 is merged. However, this PR can be merged with master without conflicts.
=> Trafo cache

README.md, scarlet/__init__.py, scarlet/blend.py, scarlet/constraints.py, scarlet/operators.py, scarlet/source.py, setup.py
This PR alters the API for `Source` in order to simplify the initialization sequence and especially break the dependency on Blend to perform the source initialization. It offers more flexibility to use different initialization functions and clarify what needs to be present for a proper Source.
It does that by defining a base class `Source`, which can be constructed only if sed, morphology, center, and constraints are defined. It's the duty of any derived class to do so. For convenience, I've implemented `PointSource` and `ExtendedSource`, with default inits and constraints (positivity, symmetry, monotonicity) that we've been using on sims and real data.
For good measure, I've also cleaned up the constraints specification. Instead of an undocumented dict, we now have a `Constraint` base …
=> New Source and Constraint API

scarlet/cache.py, scarlet/constraints.py, scarlet/source.py, scarlet/transformations.py, setup.py
This PR modifies `Constraint` to be an abstract implementation, which generates the relevant proximal operators and matrices, which are then subsequently adapted for each source.
This allows the constraints to be shared instead of copied (reducing memory cost and redundant operations) and strongly simplifies the constraint interface.
**Note:** Constraints are now generators of functions, not container of functions! This is necessary to allow the specialization for each source size.
As a bonus: factored out `Cache` to be used consistently in all modules of scarlet.
=> Abstract constraints

scarlet/blend.py, scarlet/component.py, scarlet/config.py, setup.py
uses proxmin 0.5.3 to change the box sizes on the fly.  Only important change for scarlet is that optimization parameters **cannot** be recreated, they need to be modified: https://github.com/fred3m/scarlet/compare/resize-mse?expand=1#diff-ef3b811b0e22d8a2268b81a55665ffd8R304
=> Resize without exception

docs/user_docs.ipynb, scarlet/blend.py, scarlet/observation.py, scarlet/operator.py, scarlet/source.py, scarlet/update.py, tests/test_operator.py, tests/test_source.py, tests/test_update.py
Implement symmetry in kspace and fractional pixel shifts
calculated by using the morphology centroid weighted by
the frame psf.
=> tickets/DM-20431: Implement Nate Lust's symmetry algorithm

docs/user_docs.ipynb, scarlet/blend.py, scarlet/component.py, tests/test_blend.py, tests/test_component.py
This PR addresses #114 
It does fix a lapse in our `Blend._backward` code, which iterated over sources instead of components. In essence, the code only worked for single-component sources. I've corrected that and removed the redundant `nodes` in favor of the more obvious `sources` property. I needed to adjust 2 sets of tests.
However, the main idea was to call `grad` only once instead of dynamically recomputing the gradient tree. This has *no* performance gains I could find with timeit for our user guide blend, running for 100 iterations. The take-away is that our runtime is fully dominated by computing the gradients.
=> Grad performance

scarlet/measurement.py, scarlet/source.py, scarlet/update.py, tests/test_update.py
Methods that measure something off morphologies or sed or full data cubes in the model space are put into this new module. this clarifies where such methods go, and the methods don't use the full `component` as argument and then set implicit attributes. Instead, this is now done explicitly by the `update` methods.
=> introduced measurement module

scarlet/operator.py
A quick and cheap trick to have fast shapes in symmetry. This is just a padding of the morphologies with a fast fft shape. The gain is pretty great! 
Before PR #107 the runtime for quickstart was ~20ms 
After PR #107, it went to ~80ms
Now we are back to ~20ms
=> Fastfft symmetry

docs/quickstart.ipynb, docs/user_docs.ipynb, scarlet/component.py, scarlet/source.py, scarlet/update.py, tests/test_source.py, tests/test_update.py
SED initialization code was not robust for negative/zero flux in some bands. As such, such an SED is not a problem. I therefore changed the behavior from raising an exception to logging a warning.
I also, moved the SED correction (for PSF width variations) from `get_pixel_sed` to the relevant `init_` functions because this is where it's needed. It's confusing otherwise.
=> Bugfix sed

scarlet/.pre-commit-config.yaml, scarlet/__init__.py, scarlet/bbox.py, scarlet/blend.py, scarlet/cache.py, scarlet/component.py, scarlet/constraint.py, scarlet/display.py, scarlet/fft.py, scarlet/frame.py, scarlet/interpolation.py, scarlet/measure.py, scarlet/observation.py, scarlet/operator.py, scarlet/parameter.py, scarlet/psf.py, scarlet/resampling.py, scarlet/source.py
This PR has no functionality change. It reformats the code to PEP8 by using [black](https://black.readthedocs.io/en/latest/index.html). I also added an automated pre-commit hook to maintain PEP8-compliance automatically. Install instructions are [here](https://black.readthedocs.io/en/latest/version_control_integration.html)
=> pep8 compliant code from black

docs/1-concepts.ipynb, scarlet/bbox.py, scarlet/component.py, scarlet/display.py, scarlet/frame.py, scarlet/observation.py, scarlet/parameter.py, scarlet/prior.py, scarlet/source.py, tests/test_bbox.py
BBox was inelegant because it implicitly assumed or manually forced all boxes to be in 3D. Now it works in any dimension and simply takes its dimensionality from the contained that defined on at init. The only downside is the loss of the `front`, `back`, `left`, `right` etc. properties. On the upside, as Fred and I can attest: there isn't universal agreement on what they mean, so I've chosen the python slicing syntax `start` and `stop` and made it multi-dimensional.
=> made BBox any-dimensional

scarlet/display.py, scarlet/observation.py
When there were zero weights in an observation (for example masked pixels) a division by zero created an infinite value that caused the model to never converge.
=> Fix convergence

docs/0-quickstart.ipynb, docs/1-concepts.ipynb, scarlet/constraint.py, scarlet/operator.py, scarlet/operators_pybind11.cc, scarlet/source.py, tests/test_constraint.py
* Implements flat monotonicity weighting over all three neighbor pixels, which reduces radial streaking
* Allows the user the set the monotonicity weighting scheme for each source model.
Plus some spring cleaning ... I removed the special code for nearest-neighbor monotonicity, which we haven't used anymore for more than 1 year.
=> flat monotonicity weighting

scarlet/initialization.py
It's just a few characters to pass an index as an int.
=> tiny bug-fix discovered when working with Erin. 

scarlet/blend.py, scarlet/parameter.py, scarlet/prior.py
This PR fixes a bug in the relative_step function where the step was computed by averaging over one axis of a parameter. When the parameter is a morphology, this caused vertical artifacts to appear during the optimisation process.
I also used this PR to remove a few variables that were not used.
=> relative_step bug fixed

scarlet/bbox.py
somehow the code for the union of two boxes got duplicated. This PR removes the duplicate.
=> cleanup: only one __or__

.travis.yml, docs/_static/aws_scarlet.js
One of the datasets needed to make the regression testing docs work is the list of merged branches, in order. This is stored in a DynamoDB table with the name of the branch and the index order acting as the unique keys for the table. The problem is by default git returns the branches in order with the newest first, which causes problems when the table updates on a new merge to master.
This PR fixes the problem by inverting the order of the merged branches on write (in scarlet_extensions) and requires a simple change here to invert the order again so that we correctly use the "last N commits" in the correct order.
=> Invert the load order of the merged branches

scarlet/frame.py, scarlet/observation.py
This is a fix for an inconsistency in Observation: because the PSFs are defined only for channels that are observed (and that might be fewer than in the model frame), we need to select the proper channels _before_ we convolve/resample in `render`.
There are minor clean-ups throughout the Observation code, both ordinary and LowRes, plus a few TODO notes, where I see possible improvments.
=> channel selection before convolution/resampling

.travis.yml, scarlet/psf.py
Rubin Observatory is having trouble with scarlet on python 3.8. This is a test to see if all of the tests pass. If not, this branch will contain changes to allow scarlet to pass on scarlet 3.8.
=> Use python 3.8 for Travis

scarlet/initialization.py
This PR fixes the bug seen in DC2 data where a small edge source triggers a re-initialization but the `downgrade` and `fallback` parameters are not set, resulting in small, faint sources being deblended as point sources.
=> Propagate downgrade and fallback parameters

scarlet/frame.py, scarlet/measure.py
In numpy 1.20.0 an exception is raised when using `np.int`, `np.float`, etc. since numpy no longer aliases those to `int` and `float` respectively. I made a hotfix in the lsst version of scarlet earlier this week to prevent breaking the entire stack, but we should fix this in master as well.
=> fix np.float deprecation

scarlet/initialization.py, scarlet/morphology.py, scarlet/source.py, scarlet/testing/deblend.py, tests/test_component.py
stabilize the morphology initialization at the faint/small side by making sure its at least as wide as the PSF
=> init with size of at least the PSF

scarlet/initialization.py, scarlet/observation.py, scarlet/renderer.py
As reported by #245,  non-sensical spectra arise from fitting data with strong masking, i.e. when sources are initialized in regions where one or more bands are largely unavailable. The counter-intuitive behavior is that the amplitude is very high in the masked bands, and essentially zero in the unmasked bands.
Two aspects contribute to this problem:
1. The initialization with the `set_spectra_to_match` method solves a linear problem that becomes ill-defined it a morphology vector has no (or almost no) overlap with the region of non-zero weights. If convolutions are in the forward path, this statement applies to the convolved morphology. In both cases, this yields a numerically unstable matrix inverse whenever the bulk of the source is in the masked region of a given band. The solver …
=> Spectrum initialization incorrect for strongly masked data

scarlet/renderer.py
This fixes a bug in the misalignment of multi-resolution images. 
We actually need to know the bounds of the model frame to build the slices of the renderer.
=> bug fix_data_box

scarlet/renderer.py
Corrections made to lines 322-348 of renderer.py to fix bugs in the resolution renderer's treatment of rotated images.
=> Fixing rotation angle in renderer.py

scarlet/fft.py
This patch avoids deprecation warnings.
```
DeprecationWarning: Please use `next_fast_len` from the `scipy.fftpack` namespace, the `scipy.fftpack.helper` namespace is deprecated.
```
=> Avoid next_fast_len from deprecated helper namespace

docs/0-quickstart.ipynb, scarlet/initialization.py, scarlet/source.py
This PR fixes problems identified in #282 and #283. The main change is that extended source initializations don't run the simple linear solver to get the best spectrum given their own morphology and the observation. Instead, we have been recommending using `set_spectrum_to_match`, which solves for the best-fit spectrum given _all_ morphologies in the scene. So, it's entirely sufficient, and probably safer in case of close blends, to initialize with the peak pixel.
As for #282, the linear solver now masks redundant components and throws an errors message when the problem occurs, so that the user can e.g. remove that component. This is probably the best we can do without knowing why the problem occurred in the first place.
=> Init fixes
